# For full config options, check the docs:
#    docs.serverless.com
#

service: product-service-4
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    PG_HOST: rs-ab-shop-database.cig8azdsk1jk.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: abshop
    PG_USERNAME: postgres748325
    PG_PASSWORD: 1RO1znfFLiAwaDcXVVAb

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: /**/*.test.js

package:
  individually: true

functions:
  getProducts:
    handler: handlers/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  createProduct:
    handler: handlers/createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post
  getProductById:
    handler: handlers/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
